# Generated by Django 4.2.6 on 2023-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='признак доступности товара к заказу'),
        ),
    ]
