# Generated by Django 4.2.6 on 2024-02-16 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good', '0002_goodcolor_good_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='отзыв')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='автор', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='good_reviews', to='good.goodreview', verbose_name='отзывы'),
        ),
    ]
