# Generated by Django 4.2.6 on 2024-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_goodreview_good_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='discount_value',
            field=models.CharField(choices=[('Есть скидка', 'Есть скидка'), ('Нет скидки', 'Нет скидки')], default='Нет скидки', max_length=30),
        ),
    ]
