# Generated by Django 4.2.6 on 2024-02-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good', '0004_good_discount_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=150, verbose_name='сделка')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='клиент', to=settings.AUTH_USER_MODEL)),
                ('goods', models.ManyToManyField(blank=True, related_name='goods', to='good.good', verbose_name='товары')),
            ],
        ),
    ]
