# Generated by Django 4.2.6 on 2023-12-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_goodimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='good',
            field=models.ForeignKey(blank=True, default='default_image_static\\default.jpg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='good.good'),
        ),
    ]
