# Generated by Django 4.2.6 on 2023-12-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_alter_goodimage_options_alter_goodimage_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimage',
            name='good',
            field=models.ForeignKey(blank=True, default='default_image_static/default.jpg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='good.good'),
        ),
    ]
