# Generated by Django 4.2.6 on 2024-03-15 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0006_alter_deal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='discount_procent',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='процент скидки'),
        ),
    ]
