# Generated by Django 4.2.6 on 2024-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0007_good_discount_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='comment_to_actual_price',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий к фактической цене'),
        ),
    ]
