# Generated by Django 4.2.6 on 2024-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_alter_good_comment_to_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='время доставки'),
        ),
    ]
