# Generated by Django 4.2.6 on 2024-05-29 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good', '0011_alter_favourite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='users_has_in_favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_has_in_favourite', to=settings.AUTH_USER_MODEL, verbose_name='пользователи, у которых в избранном'),
        ),
    ]
