# Generated by Django 4.2.6 on 2024-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='dafault_image_static/default.jpg', null=True, upload_to='user/', verbose_name='изображение'),
        ),
    ]
