# Generated by Django 4.2.6 on 2024-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_image_static/default.jpg', null=True, upload_to='user/', verbose_name='изображение'),
        ),
    ]
